✨ Attempting to apply the following manifest:

apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    metadata:
      name: my-job
    spec:
      containers:
      - name: my-job
        image: my-image
      restartPolicy: OnFailure


