And here is how you would use those values in a Pod:


apiVersion: v1
kind: Pod
metadata:
  name: large-mem-pod
spec:
  containers:
  - name: large-mem-container
    image: example
    resources:
      limits:
        memory: "500Mi"
      requests:
        memory: "500"
    envFrom:
    - configMapRef:
        name: resource-usage-config
