✨ Attempting to apply the following manifest:

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: container-1
    image: k8s.gcr.io/busybox
    command:
     - "/bin/sh"
     - "-c"
     - "while true; do echo hello; sleep 10; done"
  - name: container-2
    image: k8s.gcr.io/busybox
    command:
     - "/bin/sh"
     - "-c"
     - "while true; do echo world; sleep 15; done"

